services:
  db:
    image: mysql:8.0
    container_name: muebleria-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: muebleria
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: muebleria-backend
    restart: always         
    depends_on:
      - db                   
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: muebleria-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
